apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-pvc
  namespace: flask-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi